FROM debian:12
RUN apt-get update
RUN apt-get install -y iproute2
RUN apt-get install -y git
RUN apt-get install -y make
RUN apt-get install -y clang
RUN git clone https://github.com/computertalker/ft_malcolm.git
